### ISSUE TITLE
How to convert from Celcius to  fahrenheit

### ISSUE THREAD

**Issue by MBlondin** [InitialForce/UnitsNet#58]
How to convert from Celcius to  fahrenheit with Units.Net a given tempature value ?

**Comment by anjdreas** [comment]
I'm on a phone so this is from the top off my head.

double f = Temperature.FromCelsiusDegrees (100).FahrenheitDegrees;

**Comment by anjdreas** [comment]
I was close, but you probably got the idea. Did you get it working?

```csharp
double f = Temperature.FromDegreesCelsius(100)
    .DegreesFahrenheit;
```

**Comment by MBlondin** [comment]
Yes I did, thank you

Sent from my BlackBerry 10 smartphone on the TELUS network.
From: Andreas Gullberg Larsen
Sent: Tuesday, February 17, 2015 6:25 AM
To: InitialForce/UnitsNet
Reply To: InitialForce/UnitsNet
Cc: Blondin,Mathieu
Subject: Re: [UnitsNet] How to convert from Celcius to fahrenheit (#58)



I was close, but you probably got the idea. Did you get it working?

double f = Temperature.FromDegreesCelsius(100)
    .DegreesFahrenheit;

**Comment by anjdreas** [comment]
Great, I'll close this then.
