### ISSUE TITLE
ApostropheDigitGroupingCultureFormatting test not passing

### ISSUE THREAD

**Issue by anjdreas** [InitialForce/UnitsNet#60]
@bretthysuik Hey I just noticed a test is not passing on my computer. I just can't figure it out, because the code looks good. I even tried with LinqPad, and "fr-CH" culture simply does not output apostrophes. Is it possible that this is related to the locale or region settings of the computer, even if the culture is specifically specified?

Test result:
```
  String lengths are both 7. Strings differ at index 1.
  Expected: "1'111 m"
  But was:  "1 111 m"
```
LinqPad:
```11111111.122321m.ToString("#,0.##", System.Globalization.CultureInfo.CreateSpecificCulture("fr-CH"))```

Outputs: 
```11 111 111,12```

According to this SO thread it should be working as far as I can tell.
http://stackoverflow.com/a/11513242/134761

**Comment by bretthysuik** [comment]
LinqPad outputs the apostrophes for me (`11'111'111.12`) and Swiss culture (fr-CH) is the only one I've come across that uses apostrophes so we don't have another test case to compare against...

Is this only happening on your machine, or the build server as well?

**Comment by anjdreas** [comment]
So I tried running LinqPad on the build server. Got apostrophes.
Tried running LinqPad on my work dev PC. No apostrophes, same as at home.

All computers are set up kind of similar. US English Windows installed, but region and number formatting configured for Norwegian. The only common denominator I've seen so far is the working PC is running Windows 7, but the the dev PCs are both running Win 8.1.

**Comment by bretthysuik** [comment]
Swiss culture (`fr-CH` and `de-CH`) is the only one that use apostrophes (I did a search for `thousands_sep` using Unicode character `U+0027` in the locales directory on a Linux system).

`$ cd /usr/share/i18n/locales; egrep -l '^thousands_sep +"<U0027>"' *`

-------

Here's a couple things you could try:
1. Edit `UnitSystemTests.cs` as follows:
```
// Change the culture at the start of all tests instead of constantly switching after every unit test
[TestFixtureSetUp]
public void FixtureSetup()
{
    _originalUICulture = Thread.CurrentThread.CurrentUICulture;
    _originalCulture = Thread.CurrentThread.CurrentCulture;
    Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;
    Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
}

[TestFixtureTearDown]
public void FixtureTeardown()
{
    Thread.CurrentThread.CurrentUICulture = _originalUICulture;
    Thread.CurrentThread.CurrentCulture = _originalCulture;
}
```

2. Run the tests using a different test runner (e.g. the [NUnit GUI test runner application](http://www.nunit.org/index.php?p=nunit-gui&r=2.4)). Maybe the test runner process you're using is altering the thread culture without us knowing?

------

It's unlikely either of those suggestions will work, but beyond that I'm out of ideas because the unit test code looks fine...

**Comment by anjdreas** [comment]
I consider this a fairly minor thing, but what bothers me is that I seem to be missing a understanding of how cultures and number formatting works. 

For some reason, the environment/OS seem to impact how number formatting works, even when specifying a specific culture. I consider using LinqPad a good way of performing the exact same test with only the environment being the variable, so that's why I don't think the test runner or the test itself is at fault. I believe I've read somewhere that the installed locale/culture of the Windows affects how formatting works, but I don't have concrete so far. It's just weird and I'm not even sure if it can be worked around.

What OS and .NET version are you running?

**Comment by anjdreas** [comment]
According to a couple of links it seems the number formatting for fr-CH culture changed in Windows 8.1, which is what I'm running on the computers that won't output apostrophes. I think we may have a winner? Haven't found anyone describing the loss of apostrophes, but clearly decimal point has been changed from dot to comma for some reason.

https://connect.microsoft.com/VisualStudio/feedback/details/814496/incorrect-cultureinfo-definition-for-de-ch-it-ch-fr-ch-de-li-in-win8-1

http://stackoverflow.com/questions/25401434/net-microsoft-reporting-always-formats-numbers-with-commas-in-windows-8-1

**Comment by bretthysuik** [comment]
> What OS and .NET version are you running?

Win7 and .NET 4.5.1/4.0 (work computer is .NET 4.0 at home I'm on 4.5.1)

The changes in Win8.1 look to be the culprit here.

**Comment by anjdreas** [comment]
Alright, cool. I'm closing this as not-my-bug. Hopefully 8.1 is patched with a fix, although I don't consider this very important anyhow.
