### ISSUE TITLE
Add support for Xamarin Unified iOS

### ISSUE THREAD

**Issue by oysteinkrog** [InitialForce/UnitsNet#61]
New unified API no longer uses monotouch10, but "Xamarin.iOS10".
http://blog.xamarin.com/how-to-update-nuget-packages-for-64-bit/

**Comment by anjdreas** [comment]
If I understand correctly, one should not add monotouch or Xamarin.iOS targets at all in the nuget.

> The following PCL lib directory follows the recommendation:
> lib\portable-net45+win+wpa81+wp80
> Whilst the following PCL lib directory should be avoided:
> lib\portable-net45+win+wpa81+wp80+Xamarin.iOS10

The targets UnitsNet currently use are:
```portable-net45+wp80+win8+wpa81+monotouch+monoandroid``` and similar.

So, dropping monotouch/monoandroid is the solution, right?

**Comment by oysteinkrog** [comment]
Good point!

**Comment by ajpinedam** [comment]
Just to see if did understand correctly.. removing the monotouch+monoandroid from the lib name would be sufficient for this library to be API Unified compliant?

**Comment by anjdreas** [comment]
Can you give alpha2 a try? I don't have Xamarin tools installed.

https://www.nuget.org/packages/UnitsNet/3.4.0-alpha2

**Comment by anjdreas** [comment]
Apparently the upgrade went well. I'll release a stable nuget shortly.

**Comment by anjdreas** [comment]
3.4.0 is now out.
