### ISSUE TITLE
Add Horsepower unit to Power section

### ISSUE THREAD

**Issue by NNordhaus** [InitialForce/UnitsNet#65]
Horsepower = Watts / 745.699872

**Comment by anjdreas** [comment]
Thanks for the suggestion. If you want to give it a go, pull requests are always welcome!

**Comment by NNordhaus** [comment]
I just started reading the wiki in an effort to do just that!

**Comment by anjdreas** [comment]
Awesome ☺ let me know if you need any assistance.

**Comment by anjdreas** [comment]
Just checking in on this, any progress?

**Comment by NNordhaus** [comment]
Was a little hesitant as there are multiple conversion factors for Horsepower per Wikipedia, ranging from 735 to 9,809.  I think the best course of action is to add all 5 of them:
* Mechanical horsepower
* Metric horsepower
* Electric horsepower
* Boiler horsepower
* Hydraulic horsepower

**Comment by anjdreas** [comment]
I agree, sounds like the reasonable approach.

**Comment by NNordhaus** [comment]
pull request submitted

**Comment by anjdreas** [comment]
Pull request #74 .
